language: node_js
node_js:
- node
- 8
branches:
  only:
  - master
  - development
notifications:
  slack:
    secure: ZdwaAO8EPQaNkHBimCs4WpnUQz0nfXOboeHKv7iFd5RJjEdMwK6Y8zqwrAuWaR0GJIlrpFLifKQsz4M2FQbtrc2eWjmfo1IUvkqED2Dc40t3ncUIaziQPSJLOCaUnzI6yKbpNCsd2M40M/RcGVIcESiAUk9WwFoGTLGAr1c4RGYS38r7cJUTZMBsp/zUGVo5UckSqn/VMwHnOuLJlRs8EaHQTVRwuh0DBBawxMsJAHDrpXCe+ZQgbr9T5j5NFC5MfDNzLY66gDSQsdUAKVnsR5r1WD6Hro8wYaWSPIVwAIfkSFJj6MZ+cPb9MYDDqNzOK1AhAWZshIGMrf3ushbHpgffivinwPVN766769/jsmDTTPdAyNEKnp4Rj5CXHdkS4WQBSDE8QL6TLtKhNtvBp3S9JG7lONjkrjj4YdBN7RhiL/igrOuD/sudnlSsgxp8lWy9sjTxI/zgiAADxb+cToKI2ofZoUFI3YVCfPWNL37UkJTve5XsUZtZRI67JwqyagflVPng5lT0SPvreyTioGS5tKrZzIPQSEHJf819ZiAtBNqqylSo/2YOORmy5lAicqjIlMhAlZCD9IXUcASKMN9SP9BnpIRClGMzL5oBjnC27E/t4yKMYMnRfKcXlymb8D9BjtgAoV1WzDGwo69ByJJ/z9HzT1239nOugm+6ro8=
