language: node_js
node_js:
- node
- 8

notifications:
  slack:
    secure: SkWbpd2WHs2KT4qzNePJjx6GZlFbIE4XHlnywBWSqTjidLdfgtNTDC7xyTeg5Ap8jrKMwFxFeZxKj/c6s4lNZ2w44+ZhEEr2uRqi0a0RYBypkZlLO7p3qh41z0em1YvWD4WKUWzpLcabRjHRxOijVdgw4AOxs6/mRDdFN8klytw18o55xVgOzB5KAaPDxAT1Jbqa5aIOh+4uqT0yE7T0ZBt7CeU1hRy2fM8sngLOkYTcEJX8wTlABkcOTniXUde5fo1y7ev1k4OIjs9CqIwpI08n5mSqhF6yAwLOlOkYP6tbN38ceuolJjf7GXuyWLs9xZJ7Whhrbk3zDc9kw5I8sCg+Kv0iLE3oSPW224vfzjzSVUetJkMb5+xjcIvyWZfbsmc6RDe2/cZKsn/cQN949AZand0gys8kThnyG0LT5TsUqSu9ThHm/lIqz3j3ydnaly35AUd4ysrWnoAmS5ZKDnt0UmBiQ9dLBYQ66zTsiwLW30IqthRuBjT28YupDVkCkDU/4DE/t3EAIP8Xn09hNEW+dCnezSMWDXlSylHfo7h4ZHu5H9eTPvSSXKjSN6jhTH6W9UEkeXUyYpckHN1is0JbBdK4VV8Had3V1JTv4GLpJRBJCiDbYLFZ9EVuBegK2eZrZdc2Ek57b47o3N/zKTOKBmQiMhfczGeZQnGEuac=

branches:
  only:
  - master
  - development