language: node_js
node_js:
- node
- 8
branches:
  only:
  - production
  - master
  - development
notifications:
  slack:
    secure: ZdwaAO8EPQaNkHBimCs4WpnUQz0nfXOboeHKv7iFd5RJjEdMwK6Y8zqwrAuWaR0GJIlrpFLifKQsz4M2FQbtrc2eWjmfo1IUvkqED2Dc40t3ncUIaziQPSJLOCaUnzI6yKbpNCsd2M40M/RcGVIcESiAUk9WwFoGTLGAr1c4RGYS38r7cJUTZMBsp/zUGVo5UckSqn/VMwHnOuLJlRs8EaHQTVRwuh0DBBawxMsJAHDrpXCe+ZQgbr9T5j5NFC5MfDNzLY66gDSQsdUAKVnsR5r1WD6Hro8wYaWSPIVwAIfkSFJj6MZ+cPb9MYDDqNzOK1AhAWZshIGMrf3ushbHpgffivinwPVN766769/jsmDTTPdAyNEKnp4Rj5CXHdkS4WQBSDE8QL6TLtKhNtvBp3S9JG7lONjkrjj4YdBN7RhiL/igrOuD/sudnlSsgxp8lWy9sjTxI/zgiAADxb+cToKI2ofZoUFI3YVCfPWNL37UkJTve5XsUZtZRI67JwqyagflVPng5lT0SPvreyTioGS5tKrZzIPQSEHJf819ZiAtBNqqylSo/2YOORmy5lAicqjIlMhAlZCD9IXUcASKMN9SP9BnpIRClGMzL5oBjnC27E/t4yKMYMnRfKcXlymb8D9BjtgAoV1WzDGwo69ByJJ/z9HzT1239nOugm+6ro8=
deploy:
  provider: heroku
  api_key:
    secure: E6G4UuD4zWEhUZ7tcvkI1uLu9Mmh+WiRuPPysNHbpe0Xa2WPykriWPNgBqdkD+LNavVelfyeu+vBTHmR0o2rESDXTCZ7e9xQFBDqf1HHeB8UHiRmfKf+IeZi87/7lQbJz21+jPWE1JcCKlIGtDA1/Ev57Vl93wB4HeBBTKa0vg7Ynr2nTrNdEaeTErX3ufkOIIDHMQyBFIv4bsFEgZnMyFLNHmqjYK08uz+voNTQi12XVDI+FMwvuWaTn0E7pppYSE15mpiUc24tddfVJGanlF+thP6j91hmqF9f6cxVe5EUjtxg4uw5bUTs5M88c6TGlt/WD+zSv6pImW5t9Kk030f2MnCibN20+Iiaz/3mjdMWUK3olX029qmSYuF98I3lvCoJDHPLdKDTz5g+26gEVUrC8iiLOgT/CQuo1SlArDfm4a2V7j/iPyYuNwCYU+tVbj2SbC+ai3hyoQL1uMYxBbttnH6yU3A7P/LvF/UmaQ465WT3QJlGWteU0ixx6bWJUPcn9AMExT5ZeglN68/f8lsIB7HZpIBUEiYbW6tfsOLRFoH78BZALbItvktJL6CTK37zK/0IWekxSPAYI2vFqThQlh51ztgv2esyl7dDDLl425vxxMW7Lx8St4adRpf1hFLcHSk3/Psk9FxSznq2pkI9zQ7F6kJBcLYhZ9eocic=
  app: 
    master: staging-codepods
    production: codepods